# Generated by Django 4.1.4 on 2022-12-20 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_course_content_content_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='staff_id',
            new_name='staff_username',
        ),
    ]
