# Generated by Django 4.1.4 on 2022-12-21 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_staff_id_payment_staff_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='statement',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='complain',
            name='statement',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
