# Generated by Django 4.1.4 on 2022-12-21 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_announcement_statement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='course_content',
            name='course_content_description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
